# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DMS.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure



class MplCanvas(FigureCanvas):
    def __init__(self, parent=None, width=5, height=4, dpi=1000):
        fig = Figure(figsize=(width, height), dpi=dpi)
        self.axes = fig.add_subplot(111)
        self.axes.get_yaxis().set_visible(False)
        self.axes.get_xaxis().set_visible(False)
        self.axes.set(facecolor="white")
        fig.subplots_adjust(left=0.02, right=0.98, top=0.98, bottom=0.02)
        fig.set_facecolor('white')
        super(MplCanvas, self).__init__(fig)


class Ui_Form(object):
    def setupUi(self, Form):
        r = 1.2
        self.ratio = r
        Form.setObjectName("Form")
        Form.resize(896 * r, 620 * r)
        self.face_mesh = QtWidgets.QLabel(Form)
        self.face_mesh.setGeometry(QtCore.QRect(15 * r, 35 * r, 260 * r, 200 * r))
        self.face_mesh.setFrameShape(QtWidgets.QFrame.Box)
        self.face_mesh.setFrameShadow(QtWidgets.QFrame.Plain)
        self.face_mesh.setText("")
        self.face_mesh.setObjectName("face_mesh")
        self.camera_show = QtWidgets.QLabel(Form)
        self.camera_show.setGeometry(QtCore.QRect(286 * r, 10 * r, 601 * r, 480 * r))
        self.camera_show.setFrameShape(QtWidgets.QFrame.Box)
        self.camera_show.setFrameShadow(QtWidgets.QFrame.Plain)
        self.camera_show.setText("")
        self.camera_show.setObjectName("camera_show")
        self.head_pose_label = QtWidgets.QLabel(Form)
        self.head_pose_label.setGeometry(QtCore.QRect(10 * r, 5 * r, 271 * r, 31 * r))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12 * r)
        font.setBold(True)
        font.setWeight(75 * r)
        self.head_pose_label.setFont(font)
        self.head_pose_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.head_pose_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.head_pose_label.setObjectName("head_pose_label")
        # self.head_yaw = QtWidgets.QLineEdit(Form)
        # self.head_yaw.setGeometry(QtCore.QRect(40 * r, 250 * r, 41 * r, 20 * r))
        # self.head_yaw.setFrame(False)
        # self.head_yaw.setObjectName("head_yaw")
        font1 = QtGui.QFont()
        font1.setFamily("Arial")
        font1.setPointSize(8 * r)
        font1.setWeight(50 * r)
        # self.head_yaw.setFont(font1)
        # self.head_yaw_label = QtWidgets.QLabel(Form)
        # self.head_yaw_label.setGeometry(QtCore.QRect(13 * r, 250 * r, 25 * r, 16 * r))
        # self.head_yaw_label.setObjectName("head_yaw_label")
        # self.head_yaw_label.setFont(font1)
        # self.head_pitch_label = QtWidgets.QLabel(Form)
        # self.head_pitch_label.setGeometry(QtCore.QRect(99 * r, 250 * r, 31 * r, 16 * r))
        # self.head_pitch_label.setObjectName("head_pitch_label")
        # self.head_pitch_label.setFont(font1)
        # self.head_pitch = QtWidgets.QLineEdit(Form)
        # self.head_pitch.setGeometry(QtCore.QRect(139 * r, 250 * r, 41 * r, 20 * r))
        # self.head_pitch.setFrame(False)
        # self.head_pitch.setObjectName("head_pitch")
        # self.head_pitch.setFont(font1)
        # self.head_roll_label = QtWidgets.QLabel(Form)
        # self.head_roll_label.setGeometry(QtCore.QRect(200 * r, 250 * r, 31 * r, 16 * r))
        # self.head_roll_label.setObjectName("head_roll_label")
        # self.head_roll_label.setFont(font1)
        # self.head_roll = QtWidgets.QLineEdit(Form)
        # self.head_roll.setGeometry(QtCore.QRect(230 * r, 250 * r, 41 * r, 20 * r))
        # self.head_roll.setFrame(False)
        # self.head_roll.setObjectName("head_roll")
        # self.head_roll.setFont(font1)
        self.eye_state_label = QtWidgets.QLabel(Form)
        self.eye_state_label.setGeometry(QtCore.QRect(10 * r, 250 * r, 271 * r, 31 * r))
        self.eye_state_label.setFont(font)
        self.eye_state_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.eye_state_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.eye_state_label.setObjectName("eye_state_label")
        self.left_eye = QtWidgets.QLabel(Form)
        self.left_eye.setGeometry(QtCore.QRect(10 * r, 280 * r, 80 * r, 60 * r))
        self.left_eye.setFrameShape(QtWidgets.QFrame.Box)
        self.left_eye.setFrameShadow(QtWidgets.QFrame.Plain)
        self.left_eye.setText("")
        self.left_eye.setObjectName("left_eye")
        self.right_eye = QtWidgets.QLabel(Form)
        self.right_eye.setGeometry(QtCore.QRect(100 * r, 280 * r, 80 * r, 60 * r))
        self.right_eye.setFrameShape(QtWidgets.QFrame.Box)
        self.right_eye.setFrameShadow(QtWidgets.QFrame.Plain)
        self.right_eye.setText("")
        self.right_eye.setObjectName("right_eye")
        self.mouth = QtWidgets.QLabel(Form)
        self.mouth.setGeometry(QtCore.QRect(190 * r, 280 * r, 88 * r, 60 * r))
        self.mouth.setFrameShape(QtWidgets.QFrame.Box)
        self.mouth.setFrameShadow(QtWidgets.QFrame.Plain)
        self.mouth.setText("")
        self.mouth.setObjectName("mouth")
        self.left_eye_label = QtWidgets.QLabel(Form)
        self.left_eye_label.setGeometry(QtCore.QRect(26 * r, 345 * r, 61 * r, 16 * r))
        self.left_eye_label.setObjectName("left_eye_label")
        self.left_eye_label.setFont(font1)
        self.right_eye_label = QtWidgets.QLabel(Form)
        self.right_eye_label.setGeometry(QtCore.QRect(106 * r, 345 * r, 61 * r, 16 * r))
        self.right_eye_label.setObjectName("right_eye_label")
        self.right_eye_label.setFont(font1)
        self.mouth_label = QtWidgets.QLabel(Form)
        self.mouth_label.setGeometry(QtCore.QRect(216 * r, 345 * r, 61 * r, 16 * r))
        self.mouth_label.setObjectName("mouth_label")
        self.mouth_label.setFont(font1)
        self.gaze_direction_label = QtWidgets.QLabel(Form)
        self.gaze_direction_label.setGeometry(QtCore.QRect(10 * r, 360 * r, 271 * r, 31 * r))
        self.gaze_direction_label.setFont(font)
        self.gaze_direction_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.gaze_direction_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.gaze_direction_label.setObjectName("gaze_direction_label")
        self.gaze_yaw_label = QtWidgets.QLabel(Form)
        self.gaze_yaw_label.setGeometry(QtCore.QRect(10 * r, 390 * r, 25 * r, 16 * r))
        self.gaze_yaw_label.setObjectName("gaze_yaw_label")
        self.gaze_yaw_label.setFont(font1)
        self.blink_duration_label = QtWidgets.QLabel(Form)
        self.blink_duration_label.setGeometry(QtCore.QRect(170 * r, 360 * r, 110 * r, 31 * r))
        self.blink_duration_label.setObjectName("close_eyes_duration_label")
        self.blink_duration_label.setFont(font)
        self.gaze_pitch = QtWidgets.QLineEdit(Form)
        self.gaze_pitch.setGeometry(QtCore.QRect(117 * r, 390 * r, 38 * r, 20 * r))
        self.gaze_pitch.setFrame(False)
        self.gaze_pitch.setObjectName("gaze_pitch")
        self.gaze_pitch.setFont(font1)
        self.gaze_pitch_label = QtWidgets.QLabel(Form)
        self.gaze_pitch_label.setGeometry(QtCore.QRect(85 * r, 390 * r, 31 * r, 16 * r))
        self.gaze_pitch_label.setObjectName("gaze_pitch_label")
        self.gaze_pitch_label.setFont(font1)
        self.gaze_yaw = QtWidgets.QLineEdit(Form)
        self.gaze_yaw.setGeometry(QtCore.QRect(38 * r, 390 * r, 38 * r, 20 * r))
        self.gaze_yaw.setFrame(False)
        self.gaze_yaw.setObjectName("gaze_yaw")
        self.gaze_yaw.setFont(font1)
        self.blink_duration = QtWidgets.QProgressBar(Form)
        self.blink_duration.setGeometry(QtCore.QRect(170 * r, 390 * r, 110 * r, 20 * r))
        # self.blink_duration.setFrame(False)
        self.blink_duration.setRange(0, 300)
        self.blink_duration.setObjectName("close_eyes_duration")
        self.blink_duration.setFont(font1)
        self.yawn_frequency_label = QtWidgets.QLabel(Form)
        self.yawn_frequency_label.setGeometry(QtCore.QRect(10 * r, 415 * r, 131 * r, 31 * r))
        self.yawn_frequency_label.setFont(font)
        self.yawn_frequency_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.yawn_frequency_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.yawn_frequency_label.setObjectName("yawn_frequency_label")
        self.drowsiness_state_label = QtWidgets.QLabel(Form)
        self.drowsiness_state_label.setGeometry(QtCore.QRect(152 * r, 415 * r, 136 * r, 31 * r))
        self.drowsiness_state_label.setFont(font)
        self.drowsiness_state_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.drowsiness_state_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.drowsiness_state_label.setObjectName("drowsiness_state_label")

        self.draw_figure = QtWidgets.QWidget(Form)
        self.draw_figure.setObjectName("draw_figure")
        self.draw_figure.setGeometry(QtCore.QRect(10 * r, 440 * r, 270 * r, 80 * r))
        self.hLayout = QtWidgets.QHBoxLayout(self.draw_figure)
        self.hLayout.setObjectName("hLayout")
        self.hLayout.setContentsMargins(0, 0, 0, 0)
        self.canvas1 = MplCanvas(self.draw_figure, width=2, height=1, dpi=50)
        self.canvas2 = MplCanvas(self.draw_figure, width=2, height=1, dpi=50)
        self.hLayout.addWidget(self.canvas1)
        self.hLayout.addWidget(self.canvas2)

        self.button_open_camera = QtWidgets.QPushButton(Form)
        self.button_open_camera.setGeometry(QtCore.QRect(400 * r, 495 * r, 100 * r, 25 * r))
        self.button_open_camera.setObjectName("button_open_camera")
        self.button_open_camera.setFont(font1)
        self.button_close = QtWidgets.QPushButton(Form)
        self.button_close.setGeometry(QtCore.QRect(680 * r, 495 * r, 100 * r, 25 * r))
        self.button_close.setObjectName("button_close")
        self.button_close.setFont(font1)

        self.line = QtWidgets.QFrame(Form)
        self.line.setStyleSheet("background-color:#000; height:2px;")
        self.line.setGeometry(20, 645, 360, 2)
        self.quantification_label = QtWidgets.QLabel(Form)
        self.quantification_label.setGeometry(QtCore.QRect(325 * r, 526 * r, 280 * r, 20 * r))
        self.quantification_label.setFont(font)
        self.quantification_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.quantification_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.quantification_label.setObjectName("quantification_label")
        self.quantification_label.setStyleSheet("color:red;")
        self.line = QtWidgets.QFrame(Form)
        self.line.setStyleSheet("background-color:#000; height:2px;")
        self.line.setGeometry(700, 645, 360, 2)

        self.drowsiness_detection_label = QtWidgets.QLabel(Form)
        self.drowsiness_detection_label.setGeometry(QtCore.QRect(20 * r, 560 * r, 95 * r, 20 * r))
        font2 = QtGui.QFont()
        font2.setFamily("Arial")
        font2.setPointSize(10 * r)
        font2.setBold(True)
        font2.setWeight(60 * r)
        self.drowsiness_detection_label.setFont(font2)
        self.drowsiness_detection_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.drowsiness_detection_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.drowsiness_detection_label.setObjectName("drowsiness_detection_label")
        self.drowsiness_detection = QtWidgets.QProgressBar(Form)
        self.drowsiness_detection.setGeometry(QtCore.QRect(115 * r, 560 * r, 330 * r, 20 * r))
        self.drowsiness_detection.setRange(0, 100)
        self.drowsiness_detection.setObjectName("drowsiness_detection")
        self.drowsiness_detection.setFont(font1)

        self.distraction_detection_label = QtWidgets.QLabel(Form)
        self.distraction_detection_label.setGeometry(QtCore.QRect(20 * r, 590 * r, 95 * r, 20 * r))
        self.distraction_detection_label.setFont(font2)
        self.distraction_detection_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.distraction_detection_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.distraction_detection_label.setObjectName("distraction_detection_label")
        self.distraction_detection = QtWidgets.QProgressBar(Form)
        self.distraction_detection.setGeometry(QtCore.QRect(115 * r, 590 * r, 330 * r, 20 * r))
        self.distraction_detection.setRange(0, 100)
        self.distraction_detection.setObjectName("distraction_detection")
        self.distraction_detection.setFont(font1)

        self.emotion_detection_label = QtWidgets.QLabel(Form)
        self.emotion_detection_label.setGeometry(QtCore.QRect(470 * r, 590 * r, 90 * r, 20 * r))
        self.emotion_detection_label.setFont(font2)
        self.emotion_detection_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.emotion_detection_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.emotion_detection_label.setObjectName("emotion_detection_label")
        self.emotion_detection = QtWidgets.QProgressBar(Form)
        self.emotion_detection.setGeometry(QtCore.QRect(545 * r, 590 * r, 340 * r, 20 * r))
        self.emotion_detection.setRange(0, 100)
        self.emotion_detection.setObjectName("emotion_detection")
        self.emotion_detection.setFont(font1)

        self.behavior_detection_label = QtWidgets.QLabel(Form)
        self.behavior_detection_label.setGeometry(QtCore.QRect(470 * r, 560 * r, 90 * r, 20 * r))
        self.behavior_detection_label.setFont(font2)
        self.behavior_detection_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.behavior_detection_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.behavior_detection_label.setObjectName("behavior_detection_label")
        self.behavior_detection = QtWidgets.QProgressBar(Form)
        self.behavior_detection.setGeometry(QtCore.QRect(545 * r, 560 * r, 340 * r, 20 * r))
        self.behavior_detection.setRange(0, 100)
        self.behavior_detection.setObjectName("behavior_detection")
        self.behavior_detection.setFont(font1)


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.head_pose_label.setText(_translate("Form", "Head pose"))
        self.eye_state_label.setText(_translate("Form", "Eyes and mouth state"))
        self.left_eye_label.setText(_translate("Form", "Left eye"))
        self.right_eye_label.setText(_translate("Form", "Right eye"))
        self.mouth_label.setText(_translate("Form", "Mouth"))
        self.gaze_direction_label.setText(_translate("Form", "Gaze direction"))
        self.gaze_yaw_label.setText(_translate("Form", "Yaw"))
        self.blink_duration_label.setText(_translate("Form", "Close eyes"))
        self.gaze_pitch_label.setText(_translate("Form", "Pitch"))
        self.yawn_frequency_label.setText(_translate("Form", "Yawn state"))
        self.quantification_label.setText(_translate("Form", "Quantified detection results"))
        self.drowsiness_state_label.setText(_translate("Form", "Blink rate"))
        self.drowsiness_detection_label.setText(_translate("Form", "Drowsiness"))
        self.distraction_detection_label.setText(_translate("Form", "Distraction"))
        self.emotion_detection_label.setText(_translate("Form", "Emotion"))
        self.behavior_detection_label.setText(_translate("Form", "Behavior"))
        self.button_open_camera.setText(_translate("Form", "Open Camera"))
        self.button_close.setText(_translate("Form", "Exit"))


